import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import Footer from './Components/Ui/Footer'
import Header from './Components/Ui/Header'
import MobileHeader from './Components/Ui/MobileHeader'
import ContactUs from './Components/Ui/ContactUs'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <Head>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Kulim+Park:wght@700&family=M+PLUS+2:wght@600&display=swap');
        </style>
      </Head>

      <body className={roboto.className}>

        <Header />

        <MobileHeader />

        {children}

        <ContactUs />

        <Footer />
      </body>

    </html>
  )
}
